version: "3"

services:
  microservice:
    container_name: swoft-microservice
    build: docker
    ports:
      - "18306:18306"
      - "18307:18307"
      - "18308:18308"
    volumes:
      - ./src:/app
  database:
    container_name: swoft-database
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'dev'
    ports:
      - 3306:3306